(function(g,h,k,l,e){g[h]=g[h]||{};for(g[h].q=g[h].q||[];e<l.length;)k(l[e++],g[h])})(window,"extole",function(g,h){h[g]=h[g]||function(){h.q.push([g,arguments])}},["log"],0);
extole.define||function(){function g(a){a=e(a);return t[a]}function h(a,b){extole.log("error","[REQUIRE] "+a,b)}function k(a,b){if(a.length)for(var n=0;n<a.length;n++)b(a[n],n);else for(n in a)Object.prototype.hasOwnProperty.call(a,n)&&b(a[n],n)}function l(a,b){var n=[];k(a,function(a,c){n[c]=b(a,c)});return n}function e(a){return"string"!==typeof a?a:/origin-\d/.test(a)?a.substring(a.indexOf("type=")).replace(/version=\d+:/,""):a}function p(a){var b=a.split("/").slice(-1)[0],n=b.length;k(b.toLowerCase(),
function(a){n+=" abcdefghijklmnopqrstuvwxyz1234567890-_.".indexOf(a)});return a.replace("origin","origin-"+n%8)}function d(a){var b=/^extole-creatives:/.test(a),c=/^extole-media:/.test(a),m=/^core-root:\/\//.test(a),f=/^extole-assets:/.test(a),n=/origin\./.test(a),u=/^http:/.test(a),e=/^https:/.test(a);return b?(a=a.slice(17),d("extole-assets:/core-modules/"+a)):f?(a=a.slice(14),d("extole-media:/assets/"+a)):c?(a=a.slice(13),a=extole.CORE_ROOT+a,d(a)):m?(a=a.slice(12),a=extole.CORE_ROOT+a,d(a)):n?
(a=p(a),a+="?site="+window.location.hostname,d(a)):u?(a=a.slice(5),d(a)):e?(a=a.slice(6),d(a)):a}function f(){}function b(){var a="undefined"!==typeof window.opera&&"[object Opera]"===window.opera.toString(),b=document.createElement("script");this.useInteractive=b.attachEvent&&!(b.attachEvent.toString&&0>b.attachEvent.toString().indexOf("[native code"))&&!a}function a(){k(t,function(a){a._fetched?a._defined||a.define():a.fetch()})}function c(a,b,c,m,d){if("$config"!=a){var u=g(a),n=u||new f;u||(u=
e(a),t[u]=n);a&&b&&(n._fetched=!0);n.start=n.start||(new Date).getTime();n.url=n.url||a;n.dependencies=n.dependencies||b;n.config=n.config||m;n.definedCallback=n.definedCallback||c;n.isRequire=n.isRequire||d}}function m(a,b,c,m){a instanceof Array&&(m=c,c=b,b=a,a=void 0);x.addDefine({url:a,dependencies:b,definedCallback:c,config:m})}function u(){v++;return"anonymous_"+v}var t={};f.prototype={getUnresolvedDependencies:function(){var a=[];k(this.dependencies,function(b){"$config"!=b&&(b=g(b),(!b||b&&
!b._defined)&&a.push(b))});return a},getDependencies:function(){var a=this,b=[];k(a.dependencies,function(c){c="$config"==c?a.config||null:g(c).definition||null;b.push(c)});return b},define:function(){function b(b){c.definedCallback=void 0;c.definition=b;c.end=(new Date).getTime();c.timeToDefine=c.end-c.start;c._defining=!1;c._defined=!0;setTimeout(a,1)}var c=this;c.defineStartTime=c.defineStartTime||(new Date).getTime();if(!c._defining&&!c._defined&&c.dependencies)if(c._defining=!0,0<c.getUnresolvedDependencies().length)c._defining=
!1;else{var m=c.getDependencies(),d={isAsync:!1,async:function(){c.isAsync=!0;d.isAsync=c.isAsync;return function(a){b(a)}}};(function(){if(c.definedCallback){var a=c.definedCallback;a=a&&a.apply(d,m);d.isAsync||b(a)}else b(!0)})()}},fetch:function(){var a=this;a._fetching||a._fetched||(a.url?(a._fetching=!0,a.startFetchTime=(new Date).getTime(),x.loadModule(a.url,function(){a._fetching=!1;a.endFetchTime=(new Date).getTime();a.timeToFetch=a.endFetchTime-a.startFetchTime;a._fetched=!0;a.define()})):
h("Tried to fetch a module without a url - dependencies: "+a.dependencies+" definedCallback: "+(a.definedCallback?"exists":"null")+" config: "+a.config))}};b.prototype={defineQueue:[],interactiveScript:null,currentlyAddingScript:null,getInteractiveScript:function(){if(x.interactiveScript&&"interactive"==x.interactiveScript.readyState)return x.interactiveScript;for(var a=document.getElementsByTagName("head")[0].getElementsByTagName("script"),b,c=a.length-1;0<=c;c--){var m=this.getScriptDataUrl(a[c]);
a[c]&&"interactive"==a[c].readyState&&m&&(b=a[c])}return b},scriptUrlAttributeName:"data-extole-require-url",getScriptDataUrl:function(a){return a.getAttribute(this.scriptUrlAttributeName)},setScriptDataUrl:function(a,b){a.setAttribute(this.scriptUrlAttributeName,b)},attachOnLoad:function(a,b){function c(f){var u=a.readyState;if(m&&"interactive"==u)this.interactiveScript=a;else if("load"===f.type||d.test(u))m?a.detachEvent("onreadystatechange",c):a.removeEventListener("load",c,!1),b(f)}b=b||function(){};
var m=this.useInteractive,d="PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/;m?a.attachEvent("onreadystatechange",c):a.addEventListener("load",c,!1)},defineTimeout:null,addDefine:function(a){if(a.url)a.url=d(a.url);else{var b=this.currentlyAddingScript||this.getInteractiveScript();this.useInteractive&&b&&(b=this.getScriptDataUrl(b),a.url=b,this.interactiveScript=null)}a.dependencies=l(a.dependencies,d);this.useInteractive&&!a.url&&h("defines should not be missing a url in ie.");
this.defineQueue.push(a);this.defineTimeout&&clearTimeout(this.defineTimeout);var c=this;this.defineTimeout=setTimeout(function(){c.intakeDefines()},1)},intakeTimeout:null,intakeDefines:function(){for(var b=[],m;m=this.defineQueue.shift();){var d=[];k(m.dependencies,function(a){a&&d.push(a)});m.url&&g(m.url);m.url||b.push("deps "+m.dependencies);k(d,function(a){c(a)});c(m.url,d,m.definedCallback,m.config,m.isRequire)}this.intakeTimeout&&clearTimeout(this.intakeTimeout);this.intakeTimeout=setTimeout(a,
1)},loadModule:function(a,b){var c=document.createElement("script");c.async=!0;c.crossOrigin="anonymous";this.setScriptDataUrl(c,a);var m=this;this.attachOnLoad(c,function(){clearTimeout(d);if(!m.useInteractive){for(var c,f=m.defineQueue.length-1;0<=f;f--)m.defineQueue[f].url||(c&&h("Multiple anonymous modules loaded in one script - "+a),c=m.defineQueue[f]);c&&(c.url=a)}m.intakeDefines();b&&b(null)});c.src=a;var d=setTimeout(function(){extole.log("warn","[REQUIRE] Module did not load within 2000ms: ",
{moduleUrl:a})},2E3);this.currentlyAddingScript=c;var f=document.getElementsByTagName("head")[0]||document.head;f?f.appendChild(c):extole.log("warn","[REQUIRE] <head> element not found on trying to load "+a,void 0);this.currentlyAddingScript=void 0}};var x=new b;m.getModule=function(a){return g(a)};var v=0;extole.define=m;extole.require=function(a,b){x.addDefine({url:u(),dependencies:a,definedCallback:b,isRequire:!0})};extole.define("extole-require",[],function(){return{resolveUrl:d}});setTimeout(function(){var a=
!1,b=[];k(t,function(c){c._defined||(a=!0);b.push({defineStartTime:c.defineStartTime,dependencies:c.dependencies,end:c.end,start:c.start,isRequire:c.isRequire,timeToDefine:c.timeToDefine,url:c.url,_defined:c._defined,_defining:c._defining,_fetched:c._fetched})});a&&extole.DUMP_REQUIRE_MODULES_ON_ERROR&&extole.log("error","After 7000ms there are unresolved extole-require modules.  ###"+JSON.stringify(b)+"###")},7E3)}();(function(){})();
extole.define("extole-uri-parser",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/collection.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/uri.js"],function(g,h){var k=/^extole_(?!zone)/,l=/^extole_zone_/;return new function(){function e(f){var b={};f=f||d;g.each(f,function(a,c){k.test(c)&&(c=c.replace(k,""),b[c]=a)});return b}function p(){var d,b,a={};this.withName=function(a){d=a;return this};this.withElementId=function(a){b=
a;return this};this.withData=function(b,m){a[b]=m;return this};this.build=function(){var c={};d&&(c.name=d);b&&(c.elementId=b);a&&(c.data=a);return c}}var d=h.deserialize(location.search);this.parseUriZoneDefinition=function(f){var b=new p,a;f=f||d;var c=e(f);g.each(c,function(a,c){b.withData(c,a)});g.each(f,function(c,d){l.test(d)&&(d=d.replace(l,""),"name"===d?(a=!0,b.withName(c)):"element_id"===d?b.withElementId(c):b.withData(d,c))});return a?b.build():null};this.parseGlobalZoneParameters=e}});
(function(g,h,k,l,e){g[h]=g[h]||{};for(g[h].q=g[h].q||[];e<l.length;)k(l[e++],g[h])})(window,"extole",function(g,h){h[g]=h[g]||function(){h.q.push([g,arguments])}},["createZone","log"],0);
(function(){var g=[{name:"Zoom Referral Program",programDomain:"zoom.extole.io",sitePatterns:"zoom.extole.io zoomdev.us *.zoomdev.us zoomext.us *.zoomext.us my.extole.com zoom.extole.io *.zoom.extole.io".split(" "),siteRegexPatterns:"zoom\\.extole\\.io\\.?$ zoomdev\\.us\\.?$ .*\\.zoomdev\\.us\\.?$ zoomext\\.us\\.?$ .*\\.zoomext\\.us\\.?$ my\\.extole\\.com\\.?$ zoom\\.extole\\.io\\.?$ .*\\.zoom\\.extole\\.io\\.?$".split(" ")},{name:"Branded Program Domain",programDomain:"rewards.zoom.us",sitePatterns:["rewards.zoom.us",
"zoom.us","*.zoom.us","go.zoom.us","*.go.zoom.us"],siteRegexPatterns:["rewards\\.zoom\\.us\\.?$","zoom\\.us\\.?$",".*\\.zoom\\.us\\.?$","go\\.zoom\\.us\\.?$",".*\\.go\\.zoom\\.us\\.?$"]}];extole.CORE_ROOT="https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145";extole.CORE_CONFIG={backendTargetingEnabled:!0,isZonePostEnabled:!1,isCookieConsentEnabled:!1,isJsCreativeRespondsWithHtmlEnabled:!1,isGlobalZoneParametersEnabled:!0,isAccessTokenIncludedInResponseEnabled:!0,cookieConsentPolicy:"COOKIE_CONSENT_OR_SESSION_COOKIE",
zonePostEnabled:!1,cookieConsentEnabled:!1};extole.CLIENT_ID="841133454";extole.BUILD_DATE="1666943127156";extole.VERSION="6.0";extole.IS_DEBUG_ENABLED=extole.debug||/[?&]extole_debug=true(&|$)/.test(location.search);extole.PROGRAM=function(){function h(b,a){b=Error.call(this,b);this.name="ExtoleError";this.message=b.message;this.stack=b.stack;this.code=a}function k(b,a){if(b.length)for(var c=0;c<b.length;c++)a(b[c],c);else for(c in b)Object.prototype.hasOwnProperty.call(b,c)&&a(b[c],c)}function l(b,
a){var c=[];k(b,function(b){(b=a(b))&&(c[c.length]=b)});return c}function e(b,a){a=a||[];var c=!1;k(a,function(a){(new RegExp(a)).test(b)&&(c=!0)});return c}function p(){extole.require(["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/uri.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/ajax.js"],function(b,a){var c=extole.CORE_ROOT;b=c.replace(/(https?:\/\/[a-z-\.]+)(\/.*)/,"$1")+"/_extole_core.gif"+b.serialize({core_root:c,
referer:window.location.hostname});a({url:b})})}h.prototype=Error();h.prototype.constructor=h;var d=function(b){var a=window.location.hostname;return l(b,function(b){if(e(a,b.siteRegexPatterns))return b})}(g),f=d[0];if(!f)throw p(),new h("No program domain is configured for hostname: "+window.location.hostname+" unable to use Extole API","site_configuration_error");1<d.length&&extole.log("warn","Multiple programs matched hostname: "+window.location.hostname+" programs: "+JSON.stringify(d));return f}();
extole.require(["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/uri.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/logger.js","create-zone-executor"],function(h,g,l){function e(){function b(b){var c=b[0];"function"===typeof a[c]?(a[c].apply(null,b[1]),extole.q.history.push({name:b[0],args:b[1],timestamp:Date.now(),stack:Error().stack})):g.warn("Unable to execute method: "+c+", it is not implemented.")}var a={log:function(){var a=
Array.prototype.slice.call(arguments),b=a[0];"function"===typeof g[b]&&g[b].apply(null,a.slice(1))},createZone:l.initiateExecution};for(extole.q.history=[];extole.q.length;)b(extole.q.shift());extole.q.push=b}function k(){extole.require(["extole-uri-parser"],function(b){var a=h.deserialize(location.search);(b=b.parseUriZoneDefinition(a))&&extole.createZone(b)})}function d(){if("function"===typeof window.onerror)var b=window.onerror;window.onerror=function(a,c,d,f,e){if(b)try{b(a,c,d,f,e)}catch(n){}c=
c||window.location.href||"no_source_or_location.href";e=e&&e.stack?e.stack:"no_error.stack";var m=[],u=JSON.stringify({MESSAGE:a,SOURCE:c,LINE_NUMBER:d,COLUMN_NUMBER:f,STACK_TRACE:e},function(a,b){if(null!==b&&"object"===typeof b){if(0<=m.indexOf(b))return;m.push(b)}return b});d=extole.PROGRAM.programDomain.split(".").join("\\.");d=new RegExp("^(http|https):\\/\\/("+d+"|(([A-Za-z0-9-]{1,}\\.){1,}|)(xtlo\\.net|extole(\\.com|\\.io)))(?=(\\/|\\?|$))");((e+a).match(/extole/i)||d.test(c))&&extole.require(["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/logger.js"],
function(a){a.error("Unhandled exception",JSON.parse(u))})}}function f(){extole._bootstrapped=!0;d();e();k()}extole.bootstrap=f;extole._bootstrapped||f();if("undefined"!==typeof window.extoleAsyncInit)try{window.extoleAsyncInit()}catch(b){extole.require(["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/logger.js"],function(a){a.error("Error executing extended core javascript. Message : "+b.message+" Stack: "+b.stack)})}})})();
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/ExtoleError.js",[],function(){function g(g,l,e,p){g=Error.call(this,g);this.name="ExtoleError";this.message=g.message||"no_message";this.stack=Error().stack;this.code=l||"extole_error";this.data=e||{};this.logLevel=0<=h.indexOf(p)?p:"error"}var h=["debug","info","warn","error"];g.prototype=Error();g.prototype.constructor=g;g.prototype.toString=function(){return this.name+" ["+this.logLevel+"]: message: "+
this.message+"; code: "+this.code+"; data: "+JSON.stringify(this.data,null,4)+"; stack trace: "+this.stack+";"};return g});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/collection.js",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/ExtoleError.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/type.js"],function(g,h){function k(e,g){var d;if(e.length===Number(e.length))for(d=0;d<e.length;d++){var f=g(e[d],d);if(!1===f)return!1}else for(d in e)if(Object.prototype.hasOwnProperty.call(e,d)&&(f=g(e[d],
d),!1===f))return!1}function l(e){if(!e||"object"!==typeof e&&!h.isPlainFunction(e))e={};for(var g=1;g<arguments.length;g++)if(h.isPlainObject(arguments[g]))for(var d in arguments[g]){var f=arguments[g][d];f!==e&&void 0!==f&&(h.isPlainObject(f)&&h.isPlainObject(e[d])?f=l(e[d],f):h.isArray(f)&&h.isArray(e[d])&&e[d].concat&&(f=e[d].concat(f)),e[d]=f)}return e}k.BREAK=!1;return{each:k,map:function(e,l){function d(a,c){b=[];k(a,function(a,d){b.push(c(a,d))})}function f(a,c){b={};k(a,function(a,d){b[d]=
c(a,d)})}var b;if(h.isArray(e))d(e,l);else if(h.isPlainObject(e))f(e,l);else throw new g(e+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return b},filter:function(e,l){function d(a,c){b=[];k(a,function(a,d){c(a,d)&&b.push(a)})}function f(a,c){b={};k(a,function(a,d){c(a,d)&&(b[d]=a)})}var b;if(h.isArray(e))d(e,l);else if(h.isPlainObject(e))f(e,l);else throw new g(e+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return b},merge:l,clone:function(e){return JSON.parse(JSON.stringify(e))},
flatten:function(e){function g(f,b){if(h.isPlainObject(f))k(f,function(a,d){var c=b.slice();c.push(d);g(a,c)});else{var a=b.join(".");d[a]=f}}if(!h.isPlainObject(e))return e;var d={};g(e,[]);return d},find:function(e,g){var d;k(e,function(f,b){if(g(f,b))return d=f,k.BREAK});return d},reverse:function(e){var g=[];if(!e||e.length!==Number(e.length))return e;for(var d=e.length-1;0<=d;d--)g.push(e[d]);return g},nashornToJs:function(e){var g=Object.prototype.toString.call(e),d;if("object"!==typeof e||
g.match(/\[object (Object|Array|Null)\]/))return e;if(g.match(/\[object java\.util\.(HashMap|TreeMap|Collections\$UnmodifiableMap)\]/)){var f={};for(d in e)f[d]=e[d]}else if("number"===typeof e.length)f=[],k(e,function(b,a){f[a]=b});else return e;return f},intersection:function(e,g){var d=[];k(e,function(f){0>g.indexOf(f)||0<=d.indexOf(f)||d.push(f)});return d},difference:function(e,g){var d=[];k(e,function(f){0<=g.indexOf(f)||0<=d.indexOf(f)||d.push(f)});return d}}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/cookie.js",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/logger.js"],function(g){function h(d){try{return decodeURIComponent(d.replace(e," "))}catch(b){return g.info("** cookie.decode ** Cookie error for: "+d,{error:b,message:b.message,stack:b.stack,cookiePart:d}),""}}function k(f){f=h(f);return 0===f.indexOf('"')?f.slice(1,-1).replace(p,'"').replace(d,"\\"):f}function l(d){if(!d||
!d.toUTCString){var b=new Date;b.setDate(b.getDate()+("number"===typeof d?d:0));return b}return d}var e=/\+/g,p=/\\"/g,d=/\\\\/g;return function(d,b,a){if(void 0!==b)return a=a||{},document.cookie=[encodeURIComponent(d),"=",encodeURIComponent(b),a.expires?"; expires="+l(a.expires).toUTCString():"",a.path?"; path="+a.path:"",a.domain?"; domain="+a.domain:"",a.samesite?"; samesite="+a.samesite:"","; secure"].join("");a:{b=document.cookie?document.cookie.split("; "):[];a=d?null:{};for(var c=0,m=b.length;c<
m;c++){var f=b[c].split("="),e=h(f[0]);if(!d)a[e]=k(f[1]);else if(d===e){d=k(f[1]);break a}}d=a}return d}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/device-type.js",[],function(){function g(g){return h.test(g)}var h=/Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|Dolphin|Fennec|(hpw|web)OS|Zune|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Silk-Accelerated|Skyfire|NetFront/i,k=/WebView|\swv|(iPhone|iPod|iPad)(?!.*Safari)|Android.*(wv|.0.0.0)|Linux; U; Android/i;return{isMobile:g,isDesktop:function(l){return!g(l)},isWebview:function(g){return k.test(g)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/dom.js",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/logger.js"],function(g){function h(a,b){return(b||document).querySelectorAll(a)}function k(a,b){return h(a,b)[0]}function l(a,c){function m(){clearTimeout(t);c(e);p.removeListener(e,"load",m)}c=c||function(){};if(b[a]||!a)return c(b[a]),b[a]||null;b[a]=document.createElement("link");var e=b[a];d.setAttribute(e,
"rel","stylesheet");d.setAttribute(e,"href",a);f.append(k("head"),e);p.addListener(e,"load",m);var t=setTimeout(function(){g.warn("Load timeout reached for stylesheet: ",{url:a});m()},5E3);return e}var e={each:function(a,b){var c;if(a.length===Number(a.length))for(c=0;c<a.length;c++){var d=b(a[c],c);if(!1===d)return!1}else for(c in a)if(Object.prototype.hasOwnProperty.call(a,c)&&(d=b(a[c],c),!1===d))return!1},extend:function(){var a,b,d=arguments[0]||{},f=1,e=arguments.length,g=!1,h=this.extend;"boolean"===
typeof d&&(g=d,d=arguments[1]||{},f=2);for("object"===typeof d||this.isFunction(d)||(d={});f<e;f++){var l=arguments[f];if(null!==l)for(a in l){var k=d[a];var q=l[a];d!==q&&(g&&q&&(this.isPlainObject(q)||(b=this.isArray(q)))?(b?(b=!1,k=k&&this.isArray(k)?k:[]):k=k&&this.isPlainObject(k)?k:{},d[a]=h(g,k,q)):void 0!==q&&(d[a]=q))}}return d},isFunction:function(a){return a&&"function"===typeof a&&a.call&&a.apply},isPlainObject:function(a){if("[object Object]"!==String(a)||a.nodeType||a.window&&a.window==
a)return!1;try{if(a.constructor&&!Object.prototype.hasOwnProperty.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}return!0},isArray:function(a){return a instanceof Array}};e.each.BREAK=!1;var p=function(){function a(a,b,d){for(var c=[],f=0;f<t.length;f++){var e=t[f];e.element==a&&e.eventType==b&&e.listener==d&&c.push({index:f,eventListener:e})}return c}function b(a){for(var b=[],d=0;d<t.length;d++){var c=t[d];c.element===a&&b.push(c)}return b}function d(a){this.originalEvent=
a;this.type=a.type;this.keyCode=a.keyCode;this.target=a.srcElement?a.srcElement:a.target}function f(b,d,c){c=a(b,d,c);0>=c.length?g.info("events.remove - Couldn't find exiting event listener for type \""+d+'" listener on element '+b):e.each(c,function(a){var c=a.index;a=a.eventListener;b.removeEventListener?b.removeEventListener(d,a.listenerWrapper,!1):b.detachEvent("on"+d,a.listenerWrapper);t.splice(c,1)})}var t=[];d.prototype={preventDefault:function(){var a=this.originalEvent;a.preventDefault?
a.preventDefault():a.returnValue=!1},stopPropagation:function(){var a=this.originalEvent;a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0}};return{addListener:function(b,c,f){function e(a){m&&(a=window.event);return f.call(b,new d(a))}if(0<a(b,c,f).length)g.warn("events.add - Listener already exists for event "+c+" on element "+b);else{var m=!b.addEventListener;t.push({element:b,eventType:c,listener:f,listenerWrapper:e});b.addEventListener?b.addEventListener(c,e,!1):b.attachEvent("on"+c,e)}},
triggerEvent:function(a,b,c){var d=document.createEvent("Event");c=e.extend({},c);var f=!1===!c.bubbles,m=!0===c.cancelable;delete c.bubbles;delete c.cancelable;d.initEvent(b,f,m);e.extend(d,c);a.dispatchEvent(d)},removeListener:f,clearListeners:function(a){a=b(a);e.each(a,function(a){f(a.element,a.eventType,a.listener)})}}}(),d=function(){function a(a){a=a.className;var b={};if(!a)return b;e.each(a.split(" "),function(a){b[a]=1});return b}function b(a){var b="";e.each(a,function(a,c){b+=" "+c});
return b.slice(1)}return{setAttribute:function(a,b,c){a.setAttribute(b,c);a[b]=c},getAttribute:function(a,b){return a.getAttribute(b)},addClass:function(c,d){var f=a(c);f[d]||(f[d]=1,c.className=b(f))},removeClass:function(c,d){var f=a(c);delete f[d];c.className=b(f)},getClassNames:function(a){return a.className.split(" ")}}}(),f=function(){function a(a){var b=document.createDocumentFragment(),c=document.createElement("div");c.innerHTML=a;e.each(c.childNodes,function(a){1==a.nodeType&&b.appendChild(a)});
return b}function b(a){var b;e.each(a.childNodes,function(a){if(!b&&1==a.nodeType)return b=a,e.each.BREAK});return b}return{prepend:function(c,d){var f=b(c),e=d;"string"===typeof d&&(e=a(d));f?c.insertBefore(e,f):c.appendChild(e)},append:function(b,c){var d=c;"string"===typeof c&&(d=a(c));b.appendChild(d)}}}(),b={};return{addEventListener:p.addListener,removeEventListener:p.removeListener,triggerEvent:p.triggerEvent,clearEventListeners:p.clearListeners,getAttribute:d.getAttribute,setAttribute:d.setAttribute,
addClass:d.addClass,removeClass:d.removeClass,getClassNames:d.getClassNames,prepend:f.prepend,append:f.append,query:h,queryFirst:k,isVisible:function(a,b){return!!(k(a,b)||{}).offsetParent},injectStylesheet:l,injectStylesheets:function(a,b){function c(a){--d||b(f)}b=b||function(){};if(0===a.length)b();else{var d=0,f=[];e.each(a,function(a){d++;setTimeout(function(){f.push(l(a,c))},1)})}},scrollIntoViewIfNeeded:function(a,b){function c(a,b){return{start:a,length:b,end:a+b}}function d(a,c){return!1===
b||c.start<a.end&&a.start<c.end?Math.min(a.start,Math.max(c.start,a.end-c.length)):(a.start+a.end-c.length)/2}function f(a,b){return{x:a,y:b,translate:function(c,d){return f(a+c,b+d)}}}function e(a,b){for(;a;)b=b.translate(a.offsetLeft,a.offsetTop),a=a.offsetParent;return b}var g=e(a,f(0,0)),l=f(a.offsetWidth,a.offsetHeight);a=a.parentNode;for(var h;a instanceof HTMLElement;)h=e(a,f(a.clientLeft,a.clientTop)),a.scrollLeft=d(c(g.x-h.x,l.x),c(a.scrollLeft,a.clientWidth)),a.scrollTop=d(c(g.y-h.y,l.y),
c(a.scrollTop,a.clientHeight)),g=g.translate(-a.scrollLeft,-a.scrollTop),a=a.parentNode}}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/event-bus.js",[],function(){function g(){function g(d,f,b,a){if(!b)return!0;if("object"===typeof b){for(var c in b)d[f].apply(d,[c,b[c]].concat(a));return!1}if(p.test(b)){b=b.split(p);c=0;for(var e=b.length;c<e;c++)d[f].apply(d,[b[c]].concat(a));return!1}return!0}function e(d,f){var b,a=-1,c=d.length,e=f[0],g=f[1],h=f[2];switch(f.length){case 0:for(;++a<c;)(b=d[a]).callback.call(b.ctx);break;case 1:for(;++a<
c;)(b=d[a]).callback.call(b.ctx,e);break;case 2:for(;++a<c;)(b=d[a]).callback.call(b.ctx,e,g);break;case 3:for(;++a<c;)(b=d[a]).callback.call(b.ctx,e,g,h);break;default:for(;++a<c;)(b=d[a]).callback.apply(b.ctx,f)}}this._events={};var p=/\s+/;this.on=function(d,f,b){if(!g(this,"on",d,[f,b])||!f)return this;this._events||(this._events={});(this._events[d]||(this._events[d]=[])).push({callback:f,context:b,ctx:b||this});return this};this.off=function(d,f,b){var a,c,e;if(!this._events||!g(this,"off",
d,[f,b]))return this;if(!d&&!f&&!b)return this._events=void 0,this;var h=d?[d]:k.keys(this._events);var l=0;for(c=h.length;l<c;l++)if(d=h[l],a=this._events[d]){var p=[];this._events[d]=p;if(f||b){var v=0;for(e=a.length;v<e;v++){var n=a[v];(f&&f!==n.callback&&f!==n.callback._callback||b&&b!==n.context)&&p.push(n)}}p.length||delete this._events[d]}return this};this.once=function(d,f,b){function a(){var e=h.call(arguments);c.off(d,a,b);f.apply(this,e)}var c=this;this.on(d,a,b);return this};this.trigger=
function(d){if(!this._events)return this;var f=h.call(arguments,1);if(!g(this,"trigger",d,f))return this;var b=this._events[d],a=this._events.all;b&&e(b,f);a&&e(a,arguments);return this}}var h=Array.prototype.slice,k={isPlainObject:function(g){if("[object Object]"!==String(g)||g.nodeType||g.window&&g.window==g)return!1;try{if(g.constructor&&!Object.prototype.hasOwnProperty.call(g.constructor.prototype,"isPrototypeOf"))return!1}catch(e){return!1}return!0},keys:function(g){if(!this.isPlainObject(g))return[];
var e=[],h;for(h in g)Object.prototype.hasOwnProperty.call(g,h)&&e.push(h);return e},_idCounter:0,uniqueId:function(g){var e=String(++this._idCounter);return g?g+e:e}};return{create:function(){return new g}}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/logger.js",[],function(){function g(a,b,c){e||(e=b.getGlobalServices().getJsLoggingService());e[a](c)}function h(e,g,h){var m=String(extole.CORE_ROOT).match(/coreAssetsVersion=(\d+)/);h=h||{};h.pageId=d;h.referer=f;h.coreAssetsVersion=m&&m[1];try{var t=[g||"no message","START_JSON",JSON.stringify(h),"END_JSON"].join(" ")}catch(n){l("Failed to stringify log's json data",{exception:n});return}if(!extole.LOG_EXCLUDE_REGEX||
!t.match(extole.LOG_EXCLUDE_REGEX)){c[t]=++c[t]||1;if(b[e]>=b[extole.LOG_LEVEL_CONSOLE]&&(g=e+" "+t,window.console))if(window.console[e.toLowerCase()])window.console[e.toLowerCase()](g);else window.console.log(g);b[e]>=b[extole.LOG_LEVEL_REMOTE]&&(g=c[t],a[g]&&k(e,t+(1<g?" log count: "+g:"")))}}function k(a,b){extole.require(["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/api.js"],function(c){c.post("/api/v4/debug/logs",{level:a,message:b},null,{headers:{"Content-Type":"application/x-www-form-urlencoded"}})})}
function l(a,b){h("ERROR",a,b)}var e;if("undefined"===typeof window)return{debug:function(a,b){g("debug",a,b)},info:function(a,b){g("info",a,b)},warn:function(a,b){g("warn",a,b)},error:function(a,b){g("error",a,b)},LOGGING_ENDPOINT:"/api/v4/debug/logs"};var p=extole.IS_DEBUG_ENABLED?"DEBUG":"OFF",d=String((new Date).getTime()),f=window.location.href,b={DEBUG:0,INFO:1,WARN:2,ERROR:3,OFF:4},a={1:!0,3:!0,10:!0,30:!0,100:!0,250:!0,500:!0,1E3:!0};extole.LOG_EXCLUDE_REGEX=extole.LOG_EXCLUDE_REGEX||void 0;
extole.LOG_LEVEL_CONSOLE=extole.LOG_LEVEL_CONSOLE||p;extole.LOG_LEVEL_REMOTE=extole.LOG_LEVEL_REMOTE||"WARN";var c={};return{debug:function(a,b){h("DEBUG",a,b)},info:function(a,b){h("INFO",a,b)},warn:function(a,b){h("WARN",a,b)},error:l,LOGGING_ENDPOINT:"/api/v4/debug/logs"}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/Timer.js",[],function(){return function(){var g=this,h;this.start=function(){if(h)throw Error("Timer.start has already been called");h=new Date;return g};this.getElapsedTime=function(){if(!h)throw Error("Timer has not been started");return new Date-h}}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/type.js",[],function(){function g(g,l){return function(e){return h(g,e,l)}}function h(g,h,e){e=e||{};g=Object.prototype.toString.call(h)==="[object "+g+"]";h=h&&e.construct?h.constructor===e.construct:!0;return(e.negate?!g:g)&&h}return{isPlainObject:g("Object",{construct:Object}),isPlainFunction:g("Function"),isArray:g("Array"),isString:g("String"),isBoolean:g("Boolean"),isNumber:g("Number"),isUndefined:g("Undefined"),
isDefined:g("Undefined",{negate:!0}),isNull:g("Null"),test:h}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/uri.js",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/collection.js"],function(g){function h(d){var f={};(function m(a,c){for(var d in a){var e=a[d],g=(c?c+".":"")+d;"[object Object]"===Object.prototype.toString.call(e)?m(e,g):"__proto__"!==g&&(f[g]=e)}})(d);return f}function k(d){try{return decodeURIComponent(d)}catch(f){return d}}function l(d,f,b){f=(f||[]).concat("object"===
typeof extole&&extole.PROGRAM?extole.PROGRAM.siteRegexPatterns:[]);b=e(b||location.href);d=e(d);return(/^https?:\/\//.test(d)?g.find(f,function(a){var b=p.exec(d);return(new RegExp(a)).test(b&&b[1])}):1)?d:b}function e(d){return d.replace(/(j|%4A|%6A)(a|%41|%61)(v|%56|%76)(a|%41|%61)(s|%53|%73)(c|%43|%63)(r|%52|%72)(i|%49|%69)(p|%50|%70)(t|%54|%74)(:|%3A)/gi,"")}var p=/^https?:\/\/([^/:?#]+)/i;return{serialize:function(d){var f="",b;for(b in d)f+="&"+encodeURIComponent(b)+"="+encodeURIComponent(String(d[b]));
return f.replace(/^&/,"?")},deserialize:function(d){var f={};if(!d)return f;d=(d.match(/^\?/)?d.slice(1):d).split("&");for(var b=0;b<d.length;b++){var a=d[b].split("="),c=k(a[0]);a=k(a[1]);"__proto__"!==c&&(f[c]=a)}return f},objectToDotNotation:h,dotNotationToObject:function(d){var f={};d=h(d);for(var b in d){for(var a=f,c=b.split("."),e=c.pop();c.length;){var g=c.shift();"__proto__"!==g&&(a[g]=a[g]||{},a=a[g])}"__proto__"!==e&&(a[e]=d[b])}return f},decodeComponent:k,encodeComponent:function(d){return encodeURIComponent(d)},
getSafeRedirectUrl:l,executeSafeRedirect:function(d,e,b){window.location.href=l(d,e,b)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/ajax.js",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/collection.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/uri.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/type.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/logger.js"],function(g,h,k,l){function e(b,
a){function c(){4!==b.readyState||A||(A=!0,String(b.status||200).match(/^[23]/)?"function"===typeof y?y.call(b,b.responseText,b):l.warn("'complete' callback must be a function."):z.call(b,b.statusText,b.status),f())}function d(a){A||(A=!0,l.error("Error with url "+w+"= "+p.join(","),e(a)),z.call(b,b.statusText,b.status))}function e(c){return{eventType:c&&c.type||null,options:a,readyState:b.readyState,response:b.response,responseText:b.responseText,responseType:b.responseType,responseURL:b.responseURL,
responseXML:b.responseXML,status:b.status,statusText:b.statusText,timeout:b.timeout,responseHeaders:b.getAllResponseHeaders()}}function f(a){0>w.indexOf(l.LOGGING_ENDPOINT)&&l.debug("ajax request complete",e(a))}var p=Array.prototype.slice.call(arguments),v=a.headers||{},n=a.xhrFields||{},w=a.url||"",q=a.data||"",r=(a.type||"get").toUpperCase(),y=a.complete||function(){},z=a.error||function(){};k.isPlainObject(q)&&("GET"===r?(w+=h.serialize(q),q=null):q=JSON.stringify(q));b.open(r,w,!0);g.merge(b,
n);g.each(v,function(a,c){try{b.setRequestHeader(c,a)}catch(E){l.error("AJAX ERROR: Couldn't set request header "+c+" to "+a)}});var A=!1;b.onload=c;b.onreadystatechange=c;b.onerror=d;b.ontimeout=d;b.onabort=f;b.send(q)}function p(b){g.each(b,function(a,c){"content-type"===c.toLowerCase()&&delete b[c]})}function d(b){b=b||{};var a=!1;for(var c=0;c<f.length;c++){try{a=f[c]()}catch(m){continue}break}e(a,b);return a}var f=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},
function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}];d.convertToFormUrlEncoded=function(b,a){function c(a){var b={};g.each(a,function(a,d){d=0<=d.indexOf(".")?'"'+d+'"':d;k.isPlainObject(a)&&(a=c(a));b[d]=a});return b}var d=[];p(b);b["content-type"]="application/x-www-form-urlencoded";a=c(a);a=g.flatten(a);g.each(b,function(a,c){"content-type"!==c.toLowerCase()&&(d.push("::headers."+c+"="+a),delete b[c])});g.each(a,function(a,b){k.isUndefined(a)||
d.push(encodeURIComponent(b)+"="+encodeURIComponent(a))});return d.join("&")};d.convertToMultipartFormData=function(b,a){var c=new FormData;g.each(a,function(a,b){c.append(b,a)});p(b);return c};return d});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/client/program.js",[],function(){return{getName:function(){return extole.PROGRAM.name},getProgramDomain:function(){return extole.PROGRAM.programDomain},getSitePatterns:function(){return extole.PROGRAM.sitePatterns},getSiteRegexPatterns:function(){return extole.PROGRAM.siteRegexPatterns},getProtocol:function(){return"https://"}}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/client/token-store.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/ExtoleError.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/collection.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/logger.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/event-bus.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/cookie.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/ajax.js".split(" "),
function(g,h,k,l,e,p){function d(){function a(a){function b(e,f){d+=1;e?5>d?c(b):(e="Failed to fetch access token after 5 attempts. Last Error: "+e.message,k.error(e),a(Error(e))):a(null,f)}var d=0;c(b)}function c(a){d("POST","/api/v5/token",null,function(b,c){a(b,c)})}function d(a,b,c,d){function e(a,b){try{var c=JSON.parse(a)}catch(D){b(D);return}b(null,c)}c=c||u();var f="https://"+extole.PROGRAM.programDomain+b+(c?"?access_token="+c:"");p({url:f,type:a,headers:{"content-type":"application/json"},
complete:function(a){e(a,d)},error:function(c,k){var l=this,q="Api request to "+b+" failed: "+k+" "+c,m={method:a,url:f,statusText:c||null,http_status_code:k||null};e(l.responseText,function(a,b){if(a){a="Failed to parse api error response as json";var c="json_parse_error";b=h.merge({response:l.responseText},m)}else a=b.message||q,c=b.code||"failed_api_request",b=h.merge({},b,m);d(new g(a,c,b))})}})}function u(){for(var a,b=0;b<q.length;b++){a=q[b];var c=a.get("extole_access_token");if("string"===
typeof c&&"undefined"!==c&&"null"!==c&&c.length)return a.get("extole_access_token")}return null}function t(a,b){var c=u();if(!a&&c)a=c;else if(!a&&!c)return;var d=c!==a;d&&x();r=0<=f.indexOf(b)&&b||(d?w():r);h.each(q,function(b){b.set("extole_access_token",a,r)});d&&y.trigger("change:access_token");c&&d&&k.debug("ACCESS_TOKEN_CHANGE - the access token changed from: "+c+", to: "+a)}function x(){r=w();h.each(q,function(a){a.remove("extole_access_token")})}function v(){this.get=function(a){return e(a)};
this.set=function(a,c,d){extole.COOKIES_DISABLED||"NO_COOKIE"===r||(e(a,c,{expires:b[d],path:"/",samesite:"strict"}),y.trigger("set:cookie",{accessToken:c,duration:d}))};this.remove=function(a){e(a,"",{expires:-1,path:"/"})}}function n(){(function(){var a="test"+(new Date).getTime();try{localStorage.setItem(a,a),localStorage.removeItem(a)}catch(A){throw Error("Local storage not supported");}})();this.get=function(a){return window.localStorage.getItem(a)};this.set=function(a,b,c){"NO_COOKIE"!==r&&
window.localStorage.setItem(a,b)};this.remove=function(a){window.localStorage.removeItem(a)}}function w(){switch(extole.CORE_CONFIG.cookieConsentPolicy){case "COOKIE_CONSENT_DISABLED":return"YEAR";case "COOKIE_CONSENT_OR_SESSION_COOKIE":return"SESSION";case "COOKIE_CONSENT_OR_NO_COOKIE":return"NO_COOKIE";default:return"NO_COOKIE"}}var q=[],r=w(),y=l.create();q.push(new function(){var a={};this.get=function(b){return a[b]};this.set=function(b,c,d){a[b]=c};this.remove=function(b){delete a[b]}});extole.COOKIES_DISABLED||
q.push(new v);if(extole.LOCAL_STORAGE_ENABLED)try{q.push(new n)}catch(z){k.info("Local Storage not supported in current browser")}this.fetch=function(b){b=b||function(){};a(function(a,c){var d=c.access_token;d&&t(d);b(a,c)})};this.getTokenDetails=function(a){a=a||function(){};d("GET","/api/v5/token",u(),a)};this.get=u;this.set=t;this.remove=x;this.events=y}var f=["NO_COOKIE","SESSION","YEAR"],b={year:365,YEAR:365,session:null,SESSION:null};return extole.tokenStore=extole.tokenStore?extole.tokenStore:
new d});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/client/metric-registry.js",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/client/program.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/ajax.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/client/token-store.js"],function(g,h,k){function l(d,e,b){b={metric_type:d,key:e,value:b};d={"Content-Type":"application/x-www-form-urlencoded",
"X-Extole-App":"javascript_sdk"};k.get()&&(d.Authorization="Bearer+"+k.get(),e=[g.getProtocol(),g.getProgramDomain(),"/api/v4/debug/metrics"].join(""),b=h.convertToFormUrlEncoded(d,b),h({url:e,type:"POST",headers:d,data:b,xhrFields:{withCredentials:!0}}))}function e(d){this.increment=function(e){l("COUNTER",d,e)}}function p(d){this.update=function(e){l("HISTOGRAM",d,e)}}return{histogram:function(d){return new p(d)},counter:function(d){return new e(d)}}});
extole.define("CreativeRenderContext",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/uri.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/collection.js"],function(g,h){function k(e,d,f){this.getElement=function(){return f};this.getName=function(){return e};this.getData=function(){return d};this.getParameters=function(){return d}}function l(){this.getName=function(){return extole.PROGRAM.name};this.getProgramDomain=function(){return extole.PROGRAM.programDomain};
this.getSitePatterns=function(){return extole.PROGRAM.sitePatterns};this.getSiteRegexPatterns=function(){return extole.PROGRAM.siteRegexPatterns}}function e(){this.backendTargetingEnabled=function(){return!0};this.cookieConsentEnabled=function(){return extole.CORE_CONFIG.isCookieConsentEnabled}}return function(p,d,f,b){var a=new k(p,d,f),c=new l,m=new e;this.getZone=function(){return a};this.getProgram=function(){return c};this.getCreativeData=function(){var b=g.dotNotationToObject(g.deserialize(location.search)),
c=g.dotNotationToObject(a.getParameters());return h.merge(b.extole_creative,c.creative)};this.getCoreConfig=function(){return m};this.getLocale=function(){return b||null}}});
extole.define("find-element-by-id",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/logger.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/client/metric-registry.js"],function(g,h){function k(g,e,h){function d(){if(e())h();else{g();var b=setTimeout;f||(f=10);var a=500<f?500:f*=1.1;b(d,a)}}var f;d()}return function(l,e){var p=(new Date).getTime(),d=extole.MILLISECONDS_TO_WARN_WHEN_ELEMENT_NOT_FOUND||3E3,f=extole.MILLISECONDS_TO_WARN_WHEN_ELEMENT_FOUND||
2E3,b=!1,a;k(function(){a=document.getElementById(l)},function(){var c=(new Date).getTime()-p,e=!!a;e&&c>=f?(h.histogram("zone_element_found_slow").update(c),g.warn("EXTOLE_ELEMENT_FOUND_SLOW: Scan duration: "+c+"ms, element id: "+l)):!b&&c>=d&&(b=!0,h.histogram("zone_element_not_yet_found").update(c),g.warn("EXTOLE_ELEMENT_NOT_YET_FOUND: Scan duration: "+c+"ms, element id: "+l));return e},function(){e(a)})}});
extole.define("ensure-element",["find-element-by-id"],function(g){return function(h,k){h.element?k(h.element):h.element_id?g(h.element_id,k):k(document.body.appendChild(document.createElement("div")))}});
extole.define("pending-zone-service","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/device-type.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/dom.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/type.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/logger.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/collection.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/client/metric-registry.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/client/token-store.js CreativeRenderContext ensure-element".split(" "),function(g,
h,k,l,e,p,d,f,b){function a(a,e){e=e||function(){};var g=a.name,k=m(a.data),l=Date.now();w(g);this.resolve=function(m,q,n,r){d.set(q,n);u(a)&&(q=c(g,"time_to_zone_response_ms"),n=Date.now()-l,p.histogram(q).update(n));b(a,function(b){a.element=b;u(a)&&t(a.element,function(){var a=c(g,"time_to_first_html_ms"),b=Date.now()-l;p.histogram(a).update(b)});h.clearEventListeners(a.element);b=new f(g,k,a.element,r);m(b);e(null,b.getZone())})}}function c(a,b){var c=document.getElementsByTagName("*").length;
c=2500<c?"xx_large":1500<c?"x_large":1E3<c?"large":500<c?"medium":"small";var d=g.isMobile((window.navigator||{}).userAgent)?"mobile":"desktop";return[a,d,c,b].join("_")}function m(a){a=e.merge({},a);delete a.campaign_id;delete a.extole_campaign_id;return a}function u(a){return v.test(a.name)||v.test((a.data||{}).redirect)?!0:!1}function t(a,b){var c=document.createElement("div");c.style.display="none";a.appendChild(c);x(c,b)}function x(a,b){if(window.MutationObserver){var c=new MutationObserver(function(d){e.each(d,
function(d){d.removedNodes&&e.each(d.removedNodes,function(d){d===a&&(b(),c.disconnect())})})});a.parentNode&&c.observe(a.parentNode,{childList:!0})}}var v=/_experience$/,n={},w=function(){var a={};return function(b){k.isUndefined(a[b])&&(a[b]=0);a[b]++;if(5===a[b]){b="duplicate_zone_requests : "+b;var c=e.filter(extole.q.history,function(a){return a.name&&"createZone"===a.name});c=e.map(c,function(a){delete (a.args[0]||{}).element;return a});l.warn(b,c)}}}();return{get:function(a){if(!n[a])throw Error("Pending zone does not exist for id: "+
a);return n[a]},create:function(){var b=Math.floor(1E9*Math.random()),c=0;return function(d,e){c++;var f=b+"."+c;n[f]=new a(d,e);return f}}()}});
extole.define("create-zone","extole-uri-parser https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/uri.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/collection.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/dom.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/client/program.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/client/token-store.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/ajax.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/ExtoleError.js pending-zone-service".split(" "),function(g,
h,k,l,e,p,d,f,b){function a(a){var b=document.createElement("script");l.setAttribute(b,"src",a);l.setAttribute(b,"async","");l.append(l.queryFirst("head")||l.queryFirst("body"),b);return b}return function(c,m,u){function t(){y&&(r.jwt=y);z&&(r.access_token=z);B&&(r.debug="true");r.extole_app="javascript_sdk";w=[A,"/zones/",c.name].join("");var b=a(w+h.serialize(r));b.onload=n;b.onerror=function(){v(new f("Zone script tag request failed","zone_tag_request_failure",null))}}function x(){var a={"Content-Type":"application/x-www-form-urlencoded",
Accept:"text/javascript","X-Extole-App":"javascript_sdk"};w=A+"/zones/"+c.name;y&&(a["X-Extole-Jwt"]=y,delete r.jwt);z&&(a.Authorization="Bearer+"+z);B&&(a["X-Extole-Debug"]="true");var b=d.convertToFormUrlEncoded(a,r);d({url:w,type:"POST",headers:a,data:b,complete:function(a,b){var c=/^text\/html(;|$)/,d=/^text\/plain(;|$)/;b=b.getResponseHeader("Content-Type");if(/^text\/javascript(;|$)/.test(b))var e=a;else c.test(b)?(c=document.createElement("div"),c.innerHTML=a,e=l.queryFirst("script",c).innerHTML):
d.test(b)&&!a?v(new f("Empty response","empty_response",null,"info")):v(new f("Received invalid content type: '"+b+"'","invalid_content_type",null,"warn"));if(e)try{(new Function(e))()}catch(C){v(new f("Error in zone script - MESSAGE: "+C.message+" STACK: "+C.stack,"zone_script_error"))}n()},error:function(a,b){try{var c=JSON.parse(this.responseText)}catch(F){c={status:b||null,statusText:a||null}}v(new f(c.message||"Ajax zone request failed",c.code||null,c))},xhrFields:{withCredentials:!0}})}function v(a){var b=
"Problem creating zone with "+(extole.CORE_CONFIG.isZonePostEnabled?"POST":"GET"),d=k.merge({originalMessage:a.message,zoneRequestUrl:w||null,zoneDefinition:c},a.data);m(new f(b,a.code||"zone_request_failed",d,a.logLevel||"error"));n()}function n(){"function"===typeof u&&setTimeout(u,500)}m=m||function(){};var w,q=h.deserialize(location.search),r=k.merge({},c.data||c.parameters),y=c.jwt||r.jwt||q.extole_jwt,z=p.get(),A=[e.getProtocol(),e.getProgramDomain()].join(""),B=r.debug&&"false"!==r.debug||
extole.IS_DEBUG_ENABLED;extole.isPassRefererInZoneData&&(r.referer=location.href);extole.CORE_CONFIG.isGlobalZoneParametersEnabled&&(q=g.parseGlobalZoneParameters(q),r=k.merge(r,q));if(extole.createZonePrehandler&&(q=extole.createZonePrehandler(c,r),!1===q)){v(new f("Zone request cancelled","zone_request_cancelled",null,"info"));return}c.element_id&&(r.element_id=c.element_id);c.data=r;r.zone_id=b.create(c,m);r=k.flatten(r);extole.CORE_CONFIG.isZonePostEnabled?x():t()}});
extole.define("create-zone-executor",["create-zone","ensure-element","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/logger.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=145/common/client/token-store.js"],function(g,h,k,l){function e(e,h,p){function n(a){if(a)t(a);else{c=!0;var b=Array.prototype.slice.call(arguments);(h||function(){}).apply(null,b);q()}}function t(b){function g(){setTimeout(function(){d(e,h,p)},1)}p+=1;if(5>p)if(f(b))c=
!1,l.remove(),g();else if("zone_tag_request_failure"!==b.code||extole.CORE_CONFIG.isAccessTokenIncludedInResponseEnabled)if("invalid_content_type"===b.code)g();else k[b.logLevel||"error"](b.toString());else a.stop(),m(function(b,d){d?c=!0:!1===d&&(c=!1,l.remove());a.start();g()});else k[b.logLevel||"error"](b.toString())}var q;a.push(function(a){q=b(a);g(e,n,q);c&&q()})}function p(a){function b(){for(;c.length;)c.shift().apply(null,arguments)}var c=[],d=!1;return function(e){c.push(e);d||(d=!0,a(function(){d=
!1;b.apply(null,arguments)}))}}function d(a,b,c){function d(){var d=!!l.get(),f=!!a.element;!extole.CORE_CONFIG.isAccessTokenIncludedInResponseEnabled&&!d||extole.isFindElementBeforeZoneRequest&&!f||e(a,b,c)}b&&k.warn("CALLBACK_PASSED_TO_CREATE_ZONE");c=Number(c)||0;l.get()||extole.CORE_CONFIG.isAccessTokenIncludedInResponseEnabled||u(d);extole.isFindElementBeforeZoneRequest&&h(a,function(b){a.element=b;d()});d()}function f(a){a=a||{};return a.data&&403===a.data.http_status_code&&("invalid_access_token"===
a.code||"expired_access_token"===a.code)}function b(a){var b=!1;return function(){var c=Array.prototype.slice.call(arguments);b||(b=!0,a.apply(null,c))}}var a=new function(){var a=0,b=[],c=this,d=!1;this.push=function(a){b.push(a);this.next()};this.next=function(){function e(){a--;c.next()}if(!d)for(;1>a&&b.length;)b.shift()(e),a++};this.start=function(){d=!1;this.next()};this.stop=function(){d=!0}},c=!1,m=p(function(a){l.getTokenDetails(function(b,c){b?f(b)?a(null,!1):a(b):a(null,0<c.expires_in)})}),
u=p(l.fetch);return{initiateExecution:d}});